/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 */

plugins {
    application
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.9.1")

    testImplementation ("io.cucumber:cucumber-java:7.4.1")
    testImplementation ("io.cucumber:cucumber-junit:7.4.1")

    implementation("com.google.guava:guava:31.1-jre")
}

application {
    mainClass.set("memo1.ejercicio1.App")
}

tasks.register<Test>("cucumberTest") {
    useJUnitPlatform()

    include("**/RunCucumberTest*")

    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()

    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
}
